function [BW] = createMask(RGB)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder app. The colorspace and
%  range for each channel of the colorspace were set within the app. The
%  segmentation mask is returned in BW, and a composite of the mask and
%  original RGB images is returned in maskedRGBImage.

% Auto-generated by colorThresholder app on 07-Sep-2018
%------------------------------------------------------


% Convert RGB image to chosen color space
I_hsv = rgb2hsv(RGB);
I_ycbcr = rgb2ycbcr(RGB);

% Define thresholds for channel 1 based on histogram settings
channel1Min = 78.000;
channel1Max = 255.000;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 138.000;
channel2Max = 164.000;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 0.000;
channel3Max = 117.000;

% Create mask based on chosen histogram thresholds
sliderBW_ycbcr = (I_ycbcr(:,:,1) >= channel1Min ) & (I_ycbcr(:,:,1) <= channel1Max) & ...
    (I_ycbcr(:,:,2) >= channel2Min ) & (I_ycbcr(:,:,2) <= channel2Max) & ...
    (I_ycbcr(:,:,3) >= channel3Min ) & (I_ycbcr(:,:,3) <= channel3Max);
BW_ycbcr = sliderBW_ycbcr;

% Define thresholds for channel 1 based on histogram settings
channel1Min = 0.483;
channel1Max = 0.589;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 0.095;
channel2Max = 0.262;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 0.718;
channel3Max = 0.957;

% Create mask based on chosen histogram thresholds
sliderBW_hsv = (I_hsv(:,:,1) >= channel1Min ) & (I_hsv(:,:,1) <= channel1Max) & ...
    (I_hsv(:,:,2) >= channel2Min ) & (I_hsv(:,:,2) <= channel2Max) & ...
    (I_hsv(:,:,3) >= channel3Min ) & (I_hsv(:,:,3) <= channel3Max);
BW_hsv = sliderBW_hsv;
BW = BW_hsv & BW_ycbcr;
end
