function [output] = writeparam(filename,param)
% writeparams - writes the nScrypt FFJ for a given project based on the two
% alignment points that are needed for the system

% Open filename
fid = fopen(filename,'w');
% Write inforamtion about the FFJ
fprintf(fid,['parameter, value\n'...
    'line_width, %.3f\n'...
    'line_height, %.3f\n'...
    'hover_height, %.3f\n'...
    'dispensegap, %.3f\n'...
    'printspeed, %.3f\n'...
    'movespeed, %.3f\n'...
    'approachspeed, %.3f\n'...
    'exitspeed, %.3f\n'...
    'openvalvedist, %.3f\n'...
    'openvalvespeed, %.3f\n'...
    'openvalvedelay, %.3f\n'...
    'closevalvespeed, %.3f\n'...
    'closevalvedelay, %.3f\n'...
    'pressure, %.3f\n'...
    'wait_time, %.3f\n'...
    ],param.line_width(1),...
    param.line_height(1),...
    param.hover_height(1),...
    param.dispensegap(1),...
    param.printspeed(1),...
    param.movespeed(1),...
    param.approachspeed(1),...
    param.exitspeed(1),...
    param.ovalve.dist(1),...
    param.ovalve.speed(1),...
    param.ovalve.delay(1),...
    param.cvalve.speed(1),...
    param.cvalve.delay(1),...
    param.pressure(1),...
    param.wait_time(1));
output = fclose(fid);
end