function [output] = writeGMJ(limits,scanDist,filename)
% writeGMJ - writes the nScrypt GMJ for a given project based on the two
% alignment points that are needed for the system
rlimits = [floor(limits(1,:)-0.5*scanDist);ceil(limits(2,:)+0.5*scanDist)];
lim = diff(rlimits(:,1:2));num = ceil(lim/scanDist)+1;
pos = rlimits(1,1:2);
[path,name] = fileparts(filename);
% Open filename
fid = fopen([path '\Scripts\' name '-gmj.gmj'],'w');
% Write inforamtion about the FFJ
fprintf(fid,['<?xml version="1.0" encoding="UTF-8"?>\n'...
    '<GridMapJob>\n'...
    '<UserUnits>Millimeters</UserUnits>\n']);
% Write Lowest Left Corner of alignment
fprintf(fid,'<LocalOffset X="%.4f" Y="%.4f" Z="%.4f" />\n',...
    pos(1,1),pos(1,2),0);
fprintf(fid,['<ScanFrequencyX>%.4f</ScanFrequencyX>\n'...
    '<ScanFrequencyY>%.4f</ScanFrequencyY>\n'],...
    scanDist,scanDist);
% Write method to find alignment point
fprintf(fid,['<Rows>%g</Rows>\n'...
    '<Columns>%g</Columns>\n'],...
    num(2),num(1));
% Write second alignment point
fprintf(fid,['<ScanDirection>POSY_POSX</ScanDirection>\n'...
    '<ScanOverlap>0</ScanOverlap>\n'...
    '<NotifyOnComplete>False</NotifyOnComplete>\n'...
    '<SaveCleanFile>True</SaveCleanFile>\n'...
    '<ScanSpeed>25</ScanSpeed>\n'...
    '<ScanPointCleaningRadius>0.5</ScanPointCleaningRadius>\n'...
    '<ScanWithStops>True</ScanWithStops>\n'...
    '<Overscan>0</Overscan>\n']);
% Write method of finding alignment point
fprintf(fid,'</GridMapJob>');
% Close FFJ file
output = fclose(fid);
end