function output = writePSJ(param,gizmo,scanDist,filename)
[path,name] = fileparts(filename);
fid = fopen([path '\Scripts\' name '-psj.psj'],'w');
fprintf(fid,['<?xml version="1.0" encoding="UTF-8"?>\n'...
    '<PrintScriptJob>\n']);
fprintf(fid,'<PrintFilePath>%s</PrintFilePath>\n',[path '\Scripts\' name '-psjscript.txt']);
fprintf(fid,'<UserUnits>Millimeters</UserUnits>\n');
fprintf(fid,'<Clearance>%.3f</Clearance>\n',param.dispensegap(1));
fprintf(fid,'<PrintResolution>%.3f</PrintResolution>\n',scanDist);
fprintf(fid,['<ReusePrevScript>False</ReusePrevScript>\n'...
    '<ScriptRotation>0.000</ScriptRotation>\n'...
    '<ScriptInvertX>False</ScriptInvertX>\n'...
  '<ScriptInvertY>False</ScriptInvertY>\n'...
  '<StartPositionOffsetX>0</StartPositionOffsetX>\n'...
  '<StartPositionOffsetY>0</StartPositionOffsetY>\n'...
  '<PerformSinglePointZAdjustment>False</PerformSinglePointZAdjustment>\n']);
fprintf(fid,'<GizmoSlotToUse>%s</GizmoSlotToUse>\n',gizmo);
fprintf(fid,['<SinglePointWaitTime>0.1</SinglePointWaitTime>\n'...
    '<PreJobDwellTime>0</PreJobDwellTime>\n']);
fprintf(fid,'</PrintScriptJob>\n');
output = fclose(fid);
end
