function [out] = writePSJscript(param,pts,filename)
% writePSJscript
%% Movement declariation
[path,name] = fileparts(filename);
fid=fopen([path '\Scripts\' name '-psjscript.txt'],'w');
n = 1;
fprintf(fid,'//%s\n',...
    strtok(name,'-'),...
    datestr(datetime));
fprintf(fid,['speed %.3f\n'...
    'move %.3f %.3f %.3f\n'],...
    param.movespeed(1),...
    pts(n,1),pts(n,2),pts(n,3));
time = param.wait_time(1); speed = 30;
for n = 2:1:size(pts,1)
    temp = 10*round(pts(n-1,4))+round(pts(n,4));
    switch temp
        case {00} % general moves, approach speed, exit speed
            if pts(n,3) < 0 % move down at approach speed
                fprintf(fid,['speed %.3f\n'...
                    'move %.3f %.3f %.3f\n'],...
                    param.approachspeed(1),...
                    pts(n,1),pts(n,2),pts(n,3));
                time = time + ...
                    norm([pts(n,1),pts(n,2),pts(n,3)])/param.approachspeed(1);
            elseif pts(n,3) > 0 % move up at exit speed and set move speed
                fprintf(fid,['speed %.3f\n'...
                    'move %.3f %.3f %.3f\n'...
                    'speed %.3f\n'],...
                    param.exitspeed(1),...
                    pts(n,1),pts(n,2),pts(n,3),...
                    param.movespeed(1));
                time = norm([pts(n,1),pts(n,2),pts(n,3)])/param.exitspeed(1);
                speed = param.movespeed(1);
            else % move at either print or move speed if no z change
                fprintf(fid,'move %.3f %.3f %.3f\n',...
                    pts(n,1),pts(n,2),pts(n,3));
                time = time + ...
                    norm([pts(n,1),pts(n,2),pts(n,3)])/speed;
            end
        case {01} % turn on print
            if time < param.wait_time(1)
                fprintf(fid,'wait %.3f // Delay for wait time...\n',...
                    param.wait_time(1)-time);
            end
            speed = param.printspeed(1).*pts(n,4);
            fprintf(fid,['valverel %.3f %.3f\n'...
                'wait %.3f\n'...
                'speed %.3f\n'...
                'move %.3f %.3f %.3f\n'],...
                param.ovalve.dist(1),param.ovalve.speed(1),...
                param.ovalve.delay(1),...
                speed,...
                pts(n,1),pts(n,2),pts(n,3));
        case {10, 20} % turn off print
            fprintf(fid,['move %.3f %.3f %.3f\n'...
                'valverel 0.000 %.3f\n'...
                'wait %.3f\n'],...
                pts(n,1),pts(n,2),pts(n,3),...
                param.cvalve.speed(1),...
                param.cvalve.delay(1));
        case {11,12,21,22} % print faster for spots
            if speed ~= param.printspeed(1)*pts(n,4)
                speed = param.printspeed(1)*pts(n,4);
                fprintf(fid,['speed %.3f\n',...
                    'move %.3f %.3f %.3f\n'],...
                    speed,...
                    pts(n,1),pts(n,2),pts(n,3));
            else
                fprintf(fid,'move %.3f %.3f %.3f\n',...
                    pts(n,1),pts(n,2),pts(n,3));
            end
        otherwise
            disp('z')
    end
end
out = fclose(fid);
end
