function [output] = writeMTP(filename)
% writeFFJ - writes the nScrypt FFJ for a given project based on the two
% alignment points that are needed for the system
[path,name] = fileparts(filename);
% Open filename
fid = fopen([path '\' name '.mtp'],'w');
% Write inforamtion about the FFJ
fprintf(fid,['<?xml version="1.0" encoding="UTF-8"?>\n'...
    '<Project id = "' name '">\n'...
    '<Settings>\n'...
    '<UserUnits>Millimeters</UserUnits>\n'...
    '</Settings>\n'...
    '<Substrate expanded="True">\n'...
    '<MasterWorkPiece id="' name '" type="WorkPiece" checked="True" enabled="True" expanded="True">\n'...
    '<Definition>' name '-wkp.wkp</Definition>\n'...
    '<Transform>\n'...
    '<Translation X="0" Y="0" Z="0" /> \n'...
    '<RotationAxis X="0.000" Y="0.000" Z="0.000" Angle="0.000" />\n'...
    '<Scale X="1.000" Y="1.000" Z="1.000" />\n'...
    '</Transform>\n'...
    '<SubPieces expanded="False" />\n'...
    '<DataGroups expanded="False" />\n'...
    '<Jobs expanded="True">\n'...
    '<Job id="Find" type="FiducialFindJob" checked="True" enabled="True" expanded="False">' name '-ffj.ffj</Job>\n'...
    '<Job id="Grid Map" type="GridMapJob" checked="True" enabled="True" expanded="False">' name '-gmj.gmj</Job>\n'...
    '<Job id="Print" type="PrintScriptJob" checked="True" enabled="True" expanded="False">' name '-psj.psj</Job>\n'...
    '</Jobs>\n'...
    '</MasterWorkPiece>\n'...
    '</Substrate>\n'...
    '<WorldMatrix M11="1" M12="0" M13="0" M14="0" M21="0" M22="1" M23="0" M24="0" M31="0" M32="0" M33="1" M34="0" M41="0" M42="0" M43="0" M44="1" />\n'...
    '</Project>\n'...
    ]);
    output = fclose(fid);
    end
