function data = spindb_sql_command(command)
% This code reproduces the data obtained using the Database Explorer app by
% connecting to a database, executing a SQL query, and importing data into the
% MATLAB(R) workspace. To use this code, add the password for connecting to the
% database in the database command.

% Auto-generated by MATLAB Version 9.4 (R2018a) and Database Toolbox Version 8.1 on 07-Feb-2019 16:27:59

%% Set preferences
prefs = setdbprefs('DataReturnFormat');
setdbprefs('DataReturnFormat','table')

%% Make connection to database
conn = database('spindb_anaren','zeke_zumbro','Fluffy11','Vendor','MYSQL','Server','10.1.93.10','PortNumber',3306);

%% Execute query and fetch results
curs = exec(conn, command); %'SELECT * FROM spindb_anaren.frameresults;');
curs = fetch(curs);
data = curs.Data;
close(curs)

%% Close connection to database
close(conn)

%% Restore preferences
setdbprefs('DataReturnFormat',prefs)

%% Clear variables
clear prefs conn curs